import React from 'react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '../services/api';
import { useFetch } from '../hooks/hooks';
import { Card, ConfusionHeat, Empty, Fig, fmt } from '../components/ui';
import { GRID, SERIES, TICK } from '../charts/palette';

/** ML research console: leaderboard (factual), ablation, latency, reproducibility. */
const ModelPerformance: React.FC = () => {
  const q = useFetch(api.performance);
  const d = q.data as any;
  if (q.loading) return <div className="page"><Empty msg="Loading…" /></div>;
  if (!d || d.status === 'no_evaluation_run_yet')
    return <div className="page"><h2>Model Performance</h2><p className="sub">ML research console.</p>
      <Card><Empty msg="No evaluation run yet. Run: python scripts/prepare_data.py, scripts/train_all.py, scripts/evaluate_all.py on CICIDS2017 data." /></Card></div>;

  const std = d.standard_metrics?.metrics ?? {};
  const rows = Object.entries(std).map(([model, v]: [string, any]) => ({ model, ...v }));
  const abl = d.ablation_metrics?.results ?? {};
  const ablRows = Object.entries(abl).map(([combo, v]: [string, any]) => ({ combo, f1: v.f1 ?? null }));
  const lat = d.latency_metrics?.stages ?? {};
  const latRows = Object.entries(lat).map(([stage, v]: [string, any]) => ({ stage, ...v }));
  const tmp = (d.temporal_metrics as any)?.windows ?? null;
  const uns = (d.unseen_attack_metrics as any) ?? null;
  const lstm = (d as any).lstm_metrics?.metrics ?? null;
  const ens = (std as any)?.ensemble ?? null;

  return (
    <div className="page">
      <h2>Model Performance</h2>
      <p className="sub">Measured results — values come from experiments, not opinion.</p>
      <div className="toolbar" aria-label="Experiment context">
        <label>Experiment <select value="std" onChange={() => {}} aria-label="Experiment">
          <option value="std">Standard (test)</option>
        </select></label>
        <label>Dataset <select value="cicids" onChange={() => {}} aria-label="Dataset">
          <option value="cicids">CICIDS2017</option>
        </select></label>
        <label>Split type <select value="strat" onChange={() => {}} aria-label="Split type">
          <option value="strat">Stratified</option>
        </select></label>
        <label>Seed <select value="42" onChange={() => {}} aria-label="Seed">
          <option value="42">42</option>
        </select></label>
      </div>
      <div className="grid" style={{ gridTemplateColumns: '3fr 2fr' }}>
        <Card title="Model results" hint="Factual measurements from experiments/results">
          <table className="tbl"><thead><tr><th>Model</th><th>Accuracy</th><th>Precision</th><th>Recall</th><th>F1</th><th>PR-AUC</th><th>FPR</th></tr></thead>
            <tbody>{rows.map((r: any) => <tr key={r.model}><td>{r.model}</td><td>{fmt(r.accuracy)}</td><td>{fmt(r.precision)}</td><td>{fmt(r.recall)}</td><td>{fmt(r.f1)}</td><td>{fmt(r.pr_auc)}</td><td>{fmt(r.fpr)}</td></tr>)}</tbody></table>
        </Card>
        <Card title="Confusion Matrix (Ensemble)" hint="Standard-protocol test split">
          {ens && ens.tp != null ? <ConfusionHeat tp={ens.tp} fp={ens.fp} tn={ens.tn} fn={ens.fn} />
            : <Empty msg="Ensemble outcomes unavailable." />}
        </Card>
      </div>
      <div className="grid" style={{ gridTemplateColumns: '1fr 1fr', marginTop: 16 }}>
        <Card title="Ablation: F1 by combination" hint="Does each component add value?">
          <ResponsiveContainer width="100%" height={240}>
            <BarChart data={ablRows.filter((r) => r.f1 != null)}><CartesianGrid strokeDasharray="3 3" stroke={GRID} />
              <XAxis dataKey="combo" tick={{ fontSize: 10 }} interval={0} angle={-18} height={60} />
              <YAxis domain={[0, 1]} tick={TICK} /><Tooltip /><Bar dataKey="f1" fill={SERIES[0]} /></BarChart>
          </ResponsiveContainer>
        </Card>
        <Card title="Latency (measured)" hint="Mean / p95 per stage">
          <table className="tbl"><thead><tr><th>Stage</th><th>Mean ms</th><th>P95 ms</th><th>Throughput</th></tr></thead>
            <tbody>{latRows.map((r: any) => <tr key={r.stage}><td>{r.stage}</td><td>{fmt(r.mean_ms)}</td><td>{fmt(r.p95_ms)}</td><td>{r.throughput_rows_per_sec ?? '—'}</td></tr>)}</tbody></table>
        </Card>
      </div>
      <Card title="Diagnostic figures" hint="Generated by evaluation/standard.py — measured on the test split">
        <div className="grid" style={{ gridTemplateColumns: '1fr 1fr' }}>
          <Fig file="confusion_matrix.png" caption="Confusion matrix (RF operating point)" />
          <Fig file="roc_curve.png" caption="ROC curve (RF attack score)" />
          <Fig file="pr_curve.png" caption="Precision–recall curve" />
          <Fig file="calibration.png" caption="Calibration curve" />
        </div>
      </Card>
      <div className="grid" style={{ gridTemplateColumns: '1fr 1fr 1fr', marginTop: 16 }}>
        <Card title="Temporal generalisation" hint="Train Mon–Thu → test Friday">
          {!tmp ? <Empty msg="Not run." /> : (
            <table className="tbl"><thead><tr><th>Window</th><th>F1</th><th>FPR</th></tr></thead>
              <tbody>{Object.entries(tmp).map(([w, v]: [string, any]) => <tr key={w}><td>{w}</td><td>{fmt(v.f1)}</td><td>{fmt(v.fpr)}</td></tr>)}</tbody></table>
          )}
        </Card>
        <Card title="Unseen attack" hint="Known vs held-out reported separately">
          {!uns ? <Empty msg="Not run." /> : (
            <dl className="kv">
              <dt>Holdout</dt><dd>{(uns.holdout_families ?? []).join(', ')}</dd>
              <dt>Known F1</dt><dd>{fmt(uns.known_attack_performance?.f1)}</dd>
              <dt>Unseen F1</dt><dd>{fmt(uns.unseen_attack_performance?.f1)}</dd>
              <dt>Unseen recall</dt><dd>{fmt(uns.unseen_attack_performance?.recall)}</dd>
            </dl>
          )}
        </Card>
        <Card title="LSTM sequences" hint="Ordered windows, label = last flow">
          {!lstm ? <Empty msg="Not run (scripts/evaluate_lstm.py)." /> : (
            <dl className="kv">
              <dt>Sequences</dt><dd>{lstm.n_sequences}</dd>
              <dt>F1</dt><dd>{fmt(lstm.f1)}</dd>
              <dt>PR-AUC</dt><dd>{fmt(lstm.pr_auc)}</dd>
              <dt>FPR</dt><dd>{fmt(lstm.fpr)}</dd>
            </dl>
          )}
        </Card>
      </div>
      <Card title="Reproducibility" hint="How to reproduce these numbers">
        <dl className="kv">
          <dt>Dataset</dt><dd>CICIDS2017 flow CSVs in data/raw (see data/README)</dd>
          <dt>Commands</dt><dd>prepare_data.py → train_all.py --seed 42 → evaluate_all.py</dd>
          <dt>Unseen-attack</dt><dd>{d.unseen_attack_metrics ? `holdout ${(d.unseen_attack_metrics.holdout_families ?? []).join(', ')}` : 'not run'}</dd>
          <dt>Temporal</dt><dd>{d.temporal_metrics ? 'computed per time window' : 'not run'}</dd>
          <dt>Commit</dt><dd>{d.standard_metrics?.git_commit ?? '—'}</dd>
        </dl>
      </Card>
    </div>
  );
};
export default ModelPerformance;
